events {}

http {
    server {
        listen 80;

        root /var/www/frontend/dist;

        location / {
            try_files $uri /index.html;
        }

        location /api1 {
            proxy_pass http://127.0.0.1:8000;
        }

        location /api2 {
            allow 127.0.0.1;
            deny all;
            proxy_pass http://127.0.0.1:8000;
        }
    }
}
